{{- if .Values.service.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vernemq.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    helm.sh/chart: {{ include "vernemq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.service.labels }}
    {{ toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
  {{- with .Values.service.api.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if (or (eq .Values.service.api.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  {{- if .Values.service.api.clusterIP }}
  clusterIP: {{ .Values.service.api.clusterIP }}
  {{- end }}
{{- else if eq .Values.service.api.type "LoadBalancer" }}
  type: {{ .Values.service.api.type }}
  {{- if .Values.service.api.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.api.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.api.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ toYaml .Values.service.api.loadBalancerSourceRanges | nindent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.service.api.type }}
{{- end }}
{{- if .Values.service.api.sessionAffinity }}
  sessionAffinity: {{ .Values.service.api.sessionAffinity }}
  {{- if .Values.service.api.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{ toYaml .Values.service.api.sessionAffinityConfig | nindent 4 }}
  {{- end -}}
{{- end }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: api
      name: api
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.api.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
